schema = 3

[mod]
  [mod."filippo.io/edwards25519"]
    version = "v1.1.0"
    hash = "sha256-9ACANrgWZSd5HYPfDZHY8DVbPSC9LOMgy8deq3rDOoc="
  [mod."github.com/Benau/go_rlottie"]
    version = "v0.0.0-20210807002906-98c1b2421989"
    hash = "sha256-oIe5oARFioEFTv/tR8V0PJGvsW1qB0/ZFo7E/UPhJX4="
  [mod."github.com/PaulSonOfLars/gotgbot/v2"]
    version = "v2.0.0-rc.29"
    hash = "sha256-xRer/hvUJ5Wv2PhMuN6fd1+oYtKwHwYCqaMXgzhpHxw="
  [mod."github.com/av-elier/go-decimal-to-rational"]
    version = "v0.0.0-20191127152832-89e6aad02ecf"
    hash = "sha256-134e6CsH7ukNl3ew3CW/8+DvBtsiaIXn5YlP1+fWUpQ="
  [mod."github.com/emersion/go-vcard"]
    version = "v0.0.0-20230815062825-8fda7d206ec9"
    hash = "sha256-tMdvTJm3jC1zwYS3CsLgSwy5+19yYygTde33Im2UxYo="
  [mod."github.com/forPelevin/gomoji"]
    version = "v1.2.0"
    hash = "sha256-OY45JcTHo1ekvmRrX5nhZ5F97/mLvD8QzvrmBfDdZCI="
  [mod."github.com/go-co-op/gocron"]
    version = "v1.37.0"
    hash = "sha256-/EAcgc/GzQP88CcvLwwi5HV01bZM7bezPfWRGRLHRTY="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.8.1"
    hash = "sha256-Vp/au38P1tf1jNTBW34rdb5mly0cde5IIXu+EMjDDUY="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.1"
    hash = "sha256-N0aiHG91gMztyWC3PAEG0JVd6B/yrcOCfdl0NzqCDXk="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/jinzhu/inflection"]
    version = "v1.0.0"
    hash = "sha256-3h3pHib5MaCXKyKLIMyQnSptDJ16kPjCOQPoEBoQsZg="
  [mod."github.com/jinzhu/now"]
    version = "v1.1.5"
    hash = "sha256-NNLqoFx9FczBBDpD0O0aSHnC/YDZ9E/xQ340o7u63IM="
  [mod."github.com/kettek/apng"]
    version = "v0.0.0-20220823221153-ff692776a607"
    hash = "sha256-VuxcQDPJsmSpueFu9ECqG/EIr29eDALA1iRpl2pquzI="
  [mod."github.com/lithammer/fuzzysearch"]
    version = "v1.1.8"
    hash = "sha256-aMMRcrlUc9CBiiNkcnWWn4hfNMNyVhrAt67kvP4D4Do="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.24"
    hash = "sha256-taGKFZFQlR5++5b2oZ1dYS3RERKv6yh1gniNWhb4egg="
  [mod."github.com/mdp/qrterminal/v3"]
    version = "v3.2.0"
    hash = "sha256-2ZcpLFu6P+a3qHH32uiFKUwzgza1NF0Bmayl41GQCEI="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/robfig/cron/v3"]
    version = "v3.0.1"
    hash = "sha256-FUdqNbWYi5biQc/tjCeqzxu4iy4ot1ZvDU1M1wRf/6k="
  [mod."github.com/rs/zerolog"]
    version = "v1.33.0"
    hash = "sha256-jT/Y/izhZiCdrDbC/ty83FGs8UQavTU+OW03O4vKFkY="
  [mod."github.com/skip2/go-qrcode"]
    version = "v0.0.0-20200617195104-da1b6568686e"
    hash = "sha256-ST9t4/b7WFXUb8wra4ZYVDNZJGrEykw8dkWhLrxp8F0="
  [mod."github.com/watgbridge/tgsconverter"]
    version = "v0.0.0-20240710075117-d1c05581b842"
    hash = "sha256-0S477WzYnjZNofoxiuYMR0Wc/elXu74WDUi7N8QoK0Q="
  [mod."github.com/watgbridge/webp"]
    version = "v0.0.0-20240709143015-99fb5316f772"
    hash = "sha256-CL7WYufOA7rxy8Tn/B8iVYa/Cf7JdIGEko2XGYoF2Fo="
  [mod."go.mau.fi/libsignal"]
    version = "v0.1.1"
    hash = "sha256-KegSskYAq2MFiOvB28WG0j0VPzfbXqivapLHwsIEYNc="
  [mod."go.mau.fi/util"]
    version = "v0.8.1"
    hash = "sha256-uq5JzOuwLpBW4wPbNfZ83L6NVlYlvSZeZdyuEl6udvQ="
  [mod."go.mau.fi/whatsmeow"]
    version = "v0.0.0-20241015144315-3fa42c3d6a28"
    hash = "sha256-IwrPWuMnlKmkssqPOgVvVGohwgJ3R/P1XvZ3j3S5GYs="
  [mod."go.uber.org/atomic"]
    version = "v1.11.0"
    hash = "sha256-TyYws/cSPVqYNffFX0gbDml1bD4bBGcysrUWU7mHPIY="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."golang.org/x/crypto"]
    version = "v0.28.0"
    hash = "sha256-AYjr0BcWQMwWY1u8c2hzUprtqHUmAH7RNSxHz2hhnZs="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20241009180824-f66d83c29e7c"
    hash = "sha256-ICL1UU2rrOBespsjNrlvrAhZOFLMcxYWAx8pDQCgAXM="
  [mod."golang.org/x/net"]
    version = "v0.30.0"
    hash = "sha256-i1f6wJHfFq0nKtbuY7twZ7uPyUbRYHVjd3uy0SS06mU="
  [mod."golang.org/x/sync"]
    version = "v0.8.0"
    hash = "sha256-usvF0z7gq1vsX58p4orX+8WHlv52pdXgaueXlwj2Wss="
  [mod."golang.org/x/sys"]
    version = "v0.26.0"
    hash = "sha256-YjklsWNhx4g4TaWRWfFe1TMFKujbqiaNvZ38bfI35fM="
  [mod."golang.org/x/term"]
    version = "v0.25.0"
    hash = "sha256-vwNqnxEcgeVxQxdKBUnkb7y9jg6LlNDJxfG1GugSeRQ="
  [mod."golang.org/x/text"]
    version = "v0.19.0"
    hash = "sha256-C92pSYLLUQ2NKKcc60wpoSJ5UWAfnWkmd997C13fXdU="
  [mod."google.golang.org/protobuf"]
    version = "v1.35.1"
    hash = "sha256-4NtUQoBvlPGFGjo7c+E1EBS/sb8oy50MGy45KGWPpWo="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."gorm.io/driver/mysql"]
    version = "v1.5.7"
    hash = "sha256-r7Ov6434mt+fbFMXwRl8wNI/ZlVimsEsEWqa+p1iKOA="
  [mod."gorm.io/driver/postgres"]
    version = "v1.5.9"
    hash = "sha256-C/ieKeHEsR0sS8kG4YZaMCkWCBRfcRC4RH5nIyWQGX4="
  [mod."gorm.io/driver/sqlite"]
    version = "v1.5.6"
    hash = "sha256-ruKKw0WUlpVkkGGO0lsaXfhy5RmbgpSJ0qEA5ICPqlA="
  [mod."gorm.io/gorm"]
    version = "v1.25.12"
    hash = "sha256-GDUgUp7FmmuNTVb+EcnhVqmPExp2VjS5vHU3m4HqGyM="
  [mod."rsc.io/qr"]
    version = "v0.2.0"
    hash = "sha256-I3fAJwwZhIrgBbCjWvIElAE9JqG2y59KRBc78EYi3RM="
