time_zone: Asia/Kolkata
time_format: 02 Jan, 2006 - Mon @ 15:04

git_executable: /usr/bin/git
go_executable: /usr/bin/go
ffmpeg_executable: /usr/bin/ffmpeg

telegram:
  bot_token: 186779
  # api_url: http://localhost:8082        # Uncomment if you have a local bot API server running (for bypassing file size limits)
  self_hosted_api: false
  owner_id: 704338780
  sudo_users_id:
    - 704338780
  target_chat_id: -100423424              # This is the chat where messages will be forwarded
  skip_video_stickers: false              # Setting this as true will stop trying to convert telegram video stickers to webp and sending them
  skip_setting_commands: false            # This will not show you list of commands when you start typing / in telegram

whatsapp:
  session_name: watgbridge        # This will appear in your Linked Devices in mobile app
  # All these values can be obtained by running /findcontacts and /getwagroups commands
  # You have to put only the values preceding the @ character
  tag_all_allowed_groups:         # Members of these groups can tag everyone by sending @all or @everyone
    - 91xxxxxxxxxx-xxxxxxxxxx
    - 91xxxxxxxxxx-xxxxxxxxxx
    - 91xxxxxxxxxx-xxxxxxxxxx
    - 12xxxxxxxxxxxxx669
  ignore_chats:
    - 91xxxxxxxxxx
    - 12xxxxxxxxxxxxx669
  status_ignored_chats:           # Statuses of these people WILL NOT BE FORWARDED to Telegram
    - 91xxxxxxxxxx
    - 1xxxxxxxxxx
  skip_documents: false
  skip_images: false
  skip_gifs: false
  skip_videos: false
  skip_voice_notes: false
  skip_audios: false
  skip_stickers: false
  skip_contacts: false
  skip_locations: false
  skip_chat_details: true
  send_revoked_message_updates: false
  # login_database:               # Uncomment only if you want to use something other than sqlite
  #   type: sqlite3
  #   url: file:wawebstore.db?foreign_keys=on


# Uncomment any on of these sections
# Using the sqlite database will be easiest as it does not require any hosted database server and stores data in a single file on your device

# database:
#   type: postgres
#   host: localhost
#   user: admin
#   password: password
#   dbname: gobot
#   port: 5432
#   time_zone: Asia/Kolkata

# database:
#   type: sqlite
#   path: ./gobot.sqlite.db

# database:
#   type: mysql
#   host: localhost
#   port: 3306
#   user: admin
#   password: password
#   dbname: gobot
